from tests.unittests.demo_parser_fixture import demo_parser  # noqa: F401
from tests.unittests.fixture_classes import (  # noqa: F401
    simple_demo_class,
    class_with_simple_demo_class,
    class_with_class_with_simple_demo_class,
    first_class_in_cycle,
    second_class_in_cycle,
    class_with_int,
    class_with_str_list,
    class_with_str_str_dict,
    class_with_simple_demo_class_list,
    class_with_generic_member,
    class_with_deep_nested_generics,
    class_with_float,
    class_with_str,
    class_with_bytes,
    class_with_bool,
    class_with_datetime,
    class_with_uuid,
    class_with_str_set,
    class_with_str_tuple,
    class_with_str_int_union,
    class_with_str_frozen_set,
    class_with_str_str_default_dict,
)
